name: Run Cypress Tests (Multiple Folders)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cypress tests for infinitx folder
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          project: ./cypress/infinix

      - name: Run Cypress tests for note_50.pro folder
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          project: ./cypress/note_50_pro