name: Run Cypress Tests (Multiple Folders)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests for infinix folder
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/infinix/*.cy.js

      - name: Run Cypress tests for note_50_pro folder
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/note_50_pro/*.cy.js
