name: Run Cypress Tests (Linear ke 3)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: | 
          npm ci

      - name: Start sysstat monitoring
        run: |
          sudo apt-get update
          sudo apt-get install -y sysstat
          mkdir -p monitoring
          sar -o monitoring/sysstat.dat 1 300 > /dev/null 2>&1 &
          echo $! > monitoring/sar_pid.txt

      - name: Run Cypress tests for infinix folder
        run: |
          npx cypress run \
            --browser chrome \
            --headed \
            --spec "cypress/e2e/infinix/*.cy.js" \
            --config chromeWebSecurity=false

      - name: Run Cypress tests for note_50_pro folder
        run: |
          npx cypress run \
            --browser chrome \
            --headed \
            --spec "cypress/e2e/note_50_pro/*.cy.js" \
            --config chromeWebSecurity=false

      - name: Stop sysstat and export JSON
        run: |
          kill $(cat monitoring/sar_pid.txt) || true
          sleep 2
          sadf -j monitoring/sysstat.dat -- -u -r -b > monitoring/report.json

      - name: Upload Monitoring Report
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-report
          path: monitoring/report.json
